const DATA = [
    {
        id : 0,
        title : " Heart necklace",
        price : 20,
        desc : "...",
        img : "/img/neck1.jpg",
        category: "Necklace",
    },
    {
        id : 1,
        title : " Flower necklace",
        price : 10,
        desc : ".",
        img : "/img/neck2.jpg",
        category: "Necklace",
    },
    {
        id : 2,
        title : "Butterfly necklace",
        price : 20,
        desc : ".",
        img : "/img/neck4.jpg",
        category: "Necklace",
    },
    {
        id : 3,
        title : "butterfly bracelet",
        price : 10,
        desc : ".",
        img : "/img/hand2.jpg",
        category: "Bracelet",
    },
    {
        id : 4,
        title : "heart braclet",
        price : 15,
        desc : ".",
        img : "/img/hand3.jpg",
        category: "Bracelet",
    },
    {
        id : 5,
        title : "heart ring",
        price : 18,
        desc : ".",
        img : "/img/bag1.jpg",
        category: "Ring",
    },
    {
        id : 6,
        title : "ring",
        price : 5,
        desc : ".",
        img : "/img/bag2.jpg",
        category: "Ring",
    },
    {
        id : 7,
        title : "butterfly ring",
        price : 10,
        desc : ".",
        img : "/img/bag3.jpg",
        category: "Ring",
    },
    {
        id : 8,
        title : " butterfly earings",
        price : 15,
        desc : ".",
        img : "/img/or1.jpg",
        category: "Earings",
    },
    {
        id : 9,
        title : " elegance earings",
        price : 20,
        desc : ".",
        img : "/img/or2.jpg",
        category: "Earings",
    },
    {
        id : 10,
        title : "flower earings",
        price : 10,
        desc : ".",
        img : "/img/or5.jpg",
        category: "Earings",
    },

]
    export default DATA;